import img from "../pexels-pixabay-164522.jpg";
const ListingDetails = {
  1: {
    id: 1,
    imageUrl: img,
    title: "Max for sale",
    address: "DHA Phase 6, Lahore",
    beds: 5,
    bath: 6,
    coveredAreaSQFT: 2350,
    propertyType: "house",
    isCommercial: false,
    price: 65000000,
    description: "Outstanding one",
  },
  2: {
    id: 2,
    imageUrl: img,
    title: "Software House for sale",
    address: "DHA Phase 6, Lahore",
    beds: 5,
    bath: 6,
    coveredAreaSQFT: 2350,
    propertyType: "house",
    isCommercial: false,
    price: 65000000,
    description: "Outstanding one",
  },
  3: {
    id: 3,
    imageUrl: img,
    title: "React House for sale",
    address: "DHA Phase 6, Lahore",
    beds: 5,
    bath: 6,
    coveredAreaSQFT: 2350,
    propertyType: "house",
    isCommercial: false,
    price: 65000000,
    description: "Outstanding one",
  },
  4: {
    id: 4,
    imageUrl: img,
    title: "1 Kanal House for sale",
    address: "DHA Phase 6, Lahore",
    beds: 5,
    bath: 6,
    coveredAreaSQFT: 2350,
    propertyType: "house",
    isCommercial: false,
    price: 65000000,
    description: "Outstanding one",
  },
  5: {
    id: 5,
    imageUrl: img,
    title: "1 Kanal House for sale",
    address: "DHA Phase 6, Lahore",
    beds: 5,
    bath: 6,
    coveredAreaSQFT: 2350,
    propertyType: "house",
    isCommercial: false,
    price: 65000000,
    description: "Outstanding one",
  },
  6: {
    id: 6,
    imageUrl: img,
    title: "1 Kanal House for sale",
    address: "DHA Phase 6, Lahore",
    beds: 5,
    bath: 6,
    coveredAreaSQFT: 2350,
    propertyType: "house",
    isCommercial: false,
    price: 65000000,
    description: "Outstanding one",
  },
  7: {
    id: 7,
    imageUrl: img,
    title: "1 Kanal House for sale",
    address: "DHA Phase 6, Lahore",
    beds: 5,
    bath: 6,
    coveredAreaSQFT: 2350,
    propertyType: "house",
    isCommercial: false,
    price: 65000000,
    description: "Outstanding one",
  },
  8: {
    id: 8,
    imageUrl: img,
    title: "1 Kanal House for sale",
    address: "DHA Phase 6, Lahore",
    beds: 5,
    bath: 6,
    coveredAreaSQFT: 2350,
    propertyType: "house",
    isCommercial: false,
    price: 65000000,
    description: "Outstanding one",
  },
  9: {
    id: 9,
    imageUrl: img,
    title: "1 Kanal House for sale",
    address: "DHA Phase 6, Lahore",
    beds: 5,
    bath: 6,
    coveredAreaSQFT: 2350,
    propertyType: "house",
    isCommercial: false,
    price: 65000000,
    description: "Outstanding one",
  },
  10: {
    id: 10,
    imageUrl: img,
    title: "1 Kanal House for sale",
    address: "DHA Phase 6, Lahore",
    beds: 5,
    bath: 6,
    coveredAreaSQFT: 2350,
    propertyType: "house",
    isCommercial: false,
    price: 65000000,
    description: "Outstanding one",
  },
  11: {
    id: 11,
    imageUrl: img,
    title: "1 Kanal House for sale",
    address: "DHA Phase 6, Lahore",
    beds: 5,
    bath: 6,
    coveredAreaSQFT: 2350,
    propertyType: "house",
    isCommercial: false,
    price: 65000000,
    description: "Outstanding one",
  },
  12: {
    id: 12,
    imageUrl: img,
    title: "1 Kanal House for sale",
    address: "DHA Phase 6, Lahore",
    beds: 5,
    bath: 6,
    coveredAreaSQFT: 2350,
    propertyType: "house",
    isCommercial: false,
    price: 65000000,
    description: "Outstanding one",
  },
  13: {
    id: 13,
    imageUrl: img,
    title: "1 Kanal House for sale",
    address: "DHA Phase 6, Lahore",
    beds: 5,
    bath: 6,
    coveredAreaSQFT: 2350,
    propertyType: "house",
    isCommercial: false,
    price: 65000000,
    description: "Outstanding one",
  },
  14: {
    id: 14,
    imageUrl: img,
    title: "1 Kanal House for sale",
    address: "DHA Phase 6, Lahore",
    beds: 5,
    bath: 6,
    coveredAreaSQFT: 2350,
    propertyType: "house",
    isCommercial: false,
    price: 65000000,
    description: "Outstanding one",
  },
  15: {
    id: 15,
    imageUrl: img,
    title: "1 Kanal House for sale",
    address: "DHA Phase 6, Lahore",
    beds: 5,
    bath: 6,
    coveredAreaSQFT: 2350,
    propertyType: "house",
    isCommercial: false,
    price: 65000000,
    description: "Outstanding one",
  },
  16: {
    id: 16,
    imageUrl: img,
    title: "1 Kanal House for sale",
    address: "DHA Phase 6, Lahore",
    beds: 5,
    bath: 6,
    coveredAreaSQFT: 2350,
    propertyType: "house",
    isCommercial: false,
    price: 65000000,
    description: "Outstanding one",
  },
  17: {
    id: 17,
    imageUrl: img,
    title: "1 Kanal House for sale",
    address: "DHA Phase 6, Lahore",
    beds: 5,
    bath: 6,
    coveredAreaSQFT: 2350,
    propertyType: "house",
    isCommercial: false,
    price: 65000000,
    description: "Outstanding one",
  },
  18: {
    id: 18,
    imageUrl: img,
    title: "1 Kanal House for sale",
    address: "DHA Phase 6, Lahore",
    beds: 5,
    bath: 6,
    coveredAreaSQFT: 2350,
    propertyType: "house",
    isCommercial: false,
    price: 65000000,
    description: "Outstanding one",
  },
  19: {
    id: 19,
    imageUrl: img,
    title: "1 Kanal House for sale",
    address: "DHA Phase 6, Lahore",
    beds: 5,
    bath: 6,
    coveredAreaSQFT: 2350,
    propertyType: "house",
    isCommercial: false,
    price: 65000000,
    description: "Outstanding one",
  },
  20: {
    id: 20,
    imageUrl: img,
    title: "1 Kanal House for sale",
    address: "DHA Phase 6, Lahore",
    beds: 5,
    bath: 6,
    coveredAreaSQFT: 2350,
    propertyType: "house",
    isCommercial: false,
    price: 65000000,
    description: "Outstanding one",
  },
};

const fetchListingDetails = async (listingId) => {
  // Simulate API call delay
  await new Promise((resolve) => setTimeout(resolve, 500));

  return ListingDetails[listingId];
};
export default fetchListingDetails;
