import img from "../pexels-pixabay-164522.jpg";
const Listings = [
  {
    id: 1,
    imageUrl: img,
    title: "Max for sale",
    address: "DHA Phase 6, Lahore",
    beds: 5,
    bath: 6,
    coveredAreaSQFT: 2350,
    propertyType: "house",
    isCommercial: false,
    price: 65000000,
  },
  {
    id: 2,
    imageUrl: img,
    title: "Soft House for sale",
    address: "DHA Phase 6, Lahore",
    beds: 5,
    bath: 6,
    coveredAreaSQFT: 2350,
    propertyType: "house",
    isCommercial: false,
    price: 65000000,
  },
  {
    id: 3,
    imageUrl: img,
    title: "React House for sale",
    address: "DHA Phase 6, Lahore",
    beds: 5,
    bath: 6,
    coveredAreaSQFT: 2350,
    propertyType: "house",
    isCommercial: false,
    price: 65000000,
  },
  {
    id: 4,
    imageUrl: img,
    title: "1 Kanal House for sale",
    address: "DHA Phase 6, Lahore",
    beds: 5,
    bath: 6,
    coveredAreaSQFT: 2350,
    propertyType: "house",
    isCommercial: false,
    price: 65000000,
  },
  {
    id: 5,
    imageUrl: img,
    title: "1 Kanal House for sale",
    address: "DHA Phase 6, Lahore",
    beds: 5,
    bath: 6,
    coveredAreaSQFT: 2350,
    propertyType: "house",
    isCommercial: false,
    price: 65000000,
  },
  {
    id: 5,
    imageUrl: img,
    title: "1 Kanal House for sale",
    address: "DHA Phase 6, Lahore",
    beds: 5,
    bath: 6,
    coveredAreaSQFT: 2350,
    propertyType: "house",
    isCommercial: false,
    price: 65000000,
  },
  {
    id: 6,
    imageUrl: img,
    title: "1 Kanal House for sale",
    address: "DHA Phase 6, Lahore",
    beds: 5,
    bath: 6,
    coveredAreaSQFT: 2350,
    propertyType: "house",
    isCommercial: false,
    price: 65000000,
  },
  {
    id: 7,
    imageUrl: img,
    title: "1 Kanal House for sale",
    address: "DHA Phase 6, Lahore",
    beds: 5,
    bath: 6,
    coveredAreaSQFT: 2350,
    propertyType: "house",
    isCommercial: false,
    price: 65000000,
  },
  {
    id: 8,
    imageUrl: img,
    title: "1 Kanal House for sale",
    address: "DHA Phase 6, Lahore",
    beds: 5,
    bath: 6,
    coveredAreaSQFT: 2350,
    propertyType: "house",
    isCommercial: false,
    price: 65000000,
  },
  {
    id: 9,
    imageUrl: img,
    title: "1 Kanal House for sale",
    address: "DHA Phase 6, Lahore",
    beds: 5,
    bath: 6,
    coveredAreaSQFT: 2350,
    propertyType: "house",
    isCommercial: false,
    price: 65000000,
  },
  {
    id: 10,
    imageUrl: img,
    title: "1 Kanal House for sale",
    address: "DHA Phase 6, Lahore",
    beds: 5,
    bath: 6,
    coveredAreaSQFT: 2350,
    propertyType: "house",
    isCommercial: false,
    price: 65000000,
  },
  {
    id: 11,
    imageUrl: img,
    title: "1 Kanal House for sale",
    address: "DHA Phase 6, Lahore",
    beds: 5,
    bath: 6,
    coveredAreaSQFT: 2350,
    propertyType: "house",
    isCommercial: false,
    price: 65000000,
  },
  {
    id: 12,
    imageUrl: img,
    title: "1 Kanal House for sale",
    address: "DHA Phase 6, Lahore",
    beds: 5,
    bath: 6,
    coveredAreaSQFT: 2350,
    propertyType: "house",
    isCommercial: false,
    price: 65000000,
  },
  {
    id: 13,
    imageUrl: img,
    title: "1 Kanal House for sale",
    address: "DHA Phase 6, Lahore",
    beds: 5,
    bath: 6,
    coveredAreaSQFT: 2350,
    propertyType: "house",
    isCommercial: false,
    price: 65000000,
  },
  {
    id: 14,
    imageUrl: img,
    title: "1 Kanal House for sale",
    address: "DHA Phase 6, Lahore",
    beds: 5,
    bath: 6,
    coveredAreaSQFT: 2350,
    propertyType: "house",
    isCommercial: false,
    price: 65000000,
  },
  {
    id: 15,
    imageUrl: img,
    title: "1 Kanal House for sale",
    address: "DHA Phase 6, Lahore",
    beds: 5,
    bath: 6,
    coveredAreaSQFT: 2350,
    propertyType: "house",
    isCommercial: false,
    price: 65000000,
  },
  {
    id: 16,
    imageUrl: img,
    title: "1 Kanal House for sale",
    address: "DHA Phase 6, Lahore",
    beds: 5,
    bath: 6,
    coveredAreaSQFT: 2350,
    propertyType: "house",
    isCommercial: false,
    price: 65000000,
  },
  {
    id: 17,
    imageUrl: img,
    title: "1 Kanal House for sale",
    address: "DHA Phase 6, Lahore",
    beds: 5,
    bath: 6,
    coveredAreaSQFT: 2350,
    propertyType: "house",
    isCommercial: false,
    price: 65000000,
  },
  {
    id: 18,
    imageUrl: img,
    title: "1 Kanal House for sale",
    address: "DHA Phase 6, Lahore",
    beds: 5,
    bath: 6,
    coveredAreaSQFT: 2350,
    propertyType: "house",
    isCommercial: false,
    price: 65000000,
  },
  {
    id: 19,
    imageUrl: img,
    title: "1 Kanal House for sale",
    address: "DHA Phase 6, Lahore",
    beds: 5,
    bath: 6,
    coveredAreaSQFT: 2350,
    propertyType: "house",
    isCommercial: false,
    price: 65000000,
  },
  {
    id: 20,
    imageUrl: img,
    title: "1 Maxgo House for sale",
    address: "DHA Phase 6, Lahore",
    beds: 5,
    bath: 6,
    coveredAreaSQFT: 2350,
    propertyType: "house",
    isCommercial: false,
    price: 65000000,
  },
];

const fetchPropertyListings = async () => {
  // Simulate API call delay
  await new Promise((resolve) => setTimeout(resolve, 500));

  return Listings;
};
export default fetchPropertyListings;
